# Name of your application. Used to uniquely configure containers.
service: fa

# Name of the container image (use your-user/app-name on external registries).
image: macpapo/fa

# Deploy to these servers.
servers:
  web:
    - 192.168.124.220

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# If used with Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
#
# Using an SSL proxy like this requires turning on config.assume_ssl and config.force_ssl in production.rb!
#
# Don't use this when deploying to multiple web servers (then you have to terminate SSL at your load balancer).
#
proxy:
  ssl: false
  app_port: 3000
  run:
    http_port: 8080
    https_port: 8443

# Where you keep your container images.
registry:
  # Alternatives: hub.docker.com / registry.digitalocean.com / ghcr.io / ...
  server: ghcr.io

  # Needed for authenticated registries.
  username: macpapo

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    THRUSTER_HTTP_PORT: "3000"
    THRUSTER_TARGET_PORT: "3001"
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    # When you start using multiple servers, you should split out job processing to a dedicated machine.
    SOLID_QUEUE_IN_PUMA: true

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "/volume1/docker/fa:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  port: "2222"
